
" Define the custom directory structure using expand() to correctly interpret environment variables
let data_path = expand('$XDG_DATA_HOME') . '/share/vim'
let config_path = expand('$XDG_CONFIG_HOME') . '/vim'
let cache_path = expand('$XDG_CACHE_HOME') . '/vim'

" Set runtimepath to include the config_path and config_path/after
execute "set runtimepath^=" . config_path . "," . config_path . "/after," . data_path

" Set the directory for swap files
execute "set dir=" . data_path

" Set viminfo file location
execute "set viminfo+=n" . cache_path . "/viminfo"

" Set undo directory and enable undo file
if has("persistent_undo")
    let &undodir=data_path . '/undodir'
    set undofile
endif

" Install plugins if not already installed
if !isdirectory(data_path . '/plugged')
    autocmd VimEnter * PlugInstall --sync
endif

" Initialize VimPlug with the custom directory
call plug#begin(data_path . '/plugged')
" List your plugins here
Plug 'rose-pine/vim'

call plug#end()

" Set theme if installed
set background=dark
silent! colorscheme rosepine

" Set line numbers
set number

" Set relative line numbers
set relativenumber

" Set tab width and indentation
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Disable line wrapping
set nowrap

" Disable swap file
set noswapfile

" Disable backup
set nobackup


" Disable highlight search
set nohlsearch

" Enable incremental search
set incsearch

" Enable 24-bit RGB color in the terminal UI
if has("termguicolors")
    set termguicolors
endif

" Set the number of lines to keep above and below the cursor
set scrolloff=8

" Always show the sign column
set signcolumn=yes

" Append '@-@' to 'isfname' option
set isfname+=@-@

" Set the update time
set updatetime=50

" Highlight the 80th column
set colorcolumn=80

" Source additional configuration files

execute 'source ' . config_path . '/keybindings.vim'

